name: Auto Commit Translations

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    environment: CI
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        npm install -g babli@latest

    - name: Run babli pull
      env:
        BABLI_API_KEY: ${{ secrets.BABLI_API_KEY }}
      run: |
        babli pull

    - name: Check for changes
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
        # Check if there are any changes
        if git diff --quiet; then
          echo "No changes detected"
        else
          echo "Changes detected"
          git add -A
          git commit -m "Translations update"
          git push
        fi